spring:
  datasource:
#    password: password123
#    url: jdbc:mysql://localhost/engineeringproject
#    username: root
    password: ${DATABASE_PASSWORD}
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}



  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true


  mail:
    host: smtp.gmail.com
    port: 587
    username: engineeringprojectwebapp@gmail.com
    password: zanhfuijlsvxxsuw
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


application:
  frontend:
    url: ${FRONTEND_URL}
  security:
    cors:
      allowed-origins: ${CORS_ALLOWED_ORIGINS}

